# Loading Libraries

In [48]:
library(dplyr)
library(RSQLite)
library(tidyr)

# Reading Soccer Sql DB

In [49]:
my_db <- src_sqlite("soccer.sqlite")

In [50]:
my_db

src:  sqlite 3.11.1 [soccer.sqlite]
tbls: Country, League, Match, Player, Player_Attributes, sqlite_sequence, Team,
  Team_Attributes

# Player Table

In [51]:
player=collect(tbl(my_db, sql("SELECT player_name,player_api_id FROM Player")))
player#  %>% select(overall_rating)

      player_name            player_api_id
1     Aaron Appindangoye     505942
2     Aaron Cresswell        155782
3     Aaron Doran            162549
4     Aaron Galindo           30572
5     Aaron Hughes            23780
6     Aaron Hunt              27316
7     Aaron Kuhl             564793
8     Aaron Lennon            30895
9     Aaron Lennox           528212
10    Aaron Meijers          101042
11    Aaron Mokoena           23889
12    Aaron Mooy             231592
13    Aaron Muirhead         163222
14    Aaron Niguez            40719
15    Aaron Ramsey            75489
16    Aaron Splaine          597948
17    Aaron Taylor-Sinclair  161644
18    Aaron Wilbraham         23499
19    Aatif Chahechouhe      120919
20    Abasse Ba               46447
21    Abdelaziz Barrada      167027
22    Abdelfettah Boukhriss  245653
23    Abdelhamid El Kaoutari 128456
24    Abdelkader Ghezzal      42664
25    Abdellah Zoubir        425950
26    Abdelmajid Oulmers      38423
27    Abdelmalek Cherrad       3264
28    Abdelmalek El Hasnaoui 467485
29    Abdelouahed Chakhsi    306735
30    Abderrazak Jadid        41659
⋮     ⋮                      ⋮
11031 Zezinho                244155
11032 Zhi Zheng               19696
11033 Zhi-Gin Lam            290868
11034 Zie Diabate            169594
11035 Ziggy Gordon           244953
11036 Ziguy Badibanga        200607
11037 Zinedine Machach       642618
11038 Zinho Gano             277772
11039 Ziri Hammar            246332
11040 Zizo                   532766
11041 Zlatan Bajramovic       27305
11042 Zlatan Ibrahimovic      35724
11043 Zlatan Ljubijankic      12574
11044 Zlatko Dedic            39494
11045 Zlatko Janjic           17233
11046 Zlatko Junuzovic        42860
11047 Zola Matumona           37128
11048 Zoltan Gera             24737
11049 Zoltan Stieber         107281
11050 Zoltan Szelesi          39801
11051 Zoran Josipovic        491794
11052 Zoran Rendulic          56929
11053 Zoran Tosic             99031
11054 Zouhaier Dhaouadhi     192132
11055 Zouhair Feddal         282473
11056 Zoumana Camara          26357
11057 Zsolt Laczko           111182
11058 Zsolt Low               36491
11059 Zurab Khizanishvili     35506
11060 Zvjezdan Misimovic      39902

In [52]:
player= as.data.frame(player)

In [53]:
df

function (x, df1, df2, ncp, log = FALSE)
{
    if (missing(ncp))
        .Call(C_df, x, df1, df2, log)
    else .Call(C_dnf, x, df1, df2, ncp, log)
}
<bytecode: 0x4499e90>
<environment: namespace:stats>

In [54]:
players<-tbl(my_db,"Player_Attributes")
league<-tbl(my_db,"League")
team<-tbl(my_db,"Team")
matches<-tbl(my_db,"Match")
team_atr<-tbl(my_db,"Team_Attributes")

#players%>% select(overall_rating)

In [55]:
class(matches)
m= as.data.frame(matches)
player_att=as.data.frame(players)
class(m)

[1] "tbl_sqlite" "tbl_sql"    "tbl_lazy"   "tbl"

[1] "data.frame"

In [56]:
playeaaar=tbl(my_db, sql("SELECT p.player_name,p.player_api_id,pr.overall_rating,pr.gk_diving,pr.gk_handling,pr.gk_kicking,pr.gk_positioning,pr.gk_reflexes FROM Player p, Player_attributes pr where  p.player_api_id=pr.player_api_id"))
collect(playeaaar)
p1=as.data.frame(playeaaar)
p1[is.na(p1)] <- 0

Warning message:
“Only first 100,000 results retrieved. Use n = Inf to retrieve all.”

       player_name        player_api_id overall_rating gk_diving gk_handling
1      Aaron Appindangoye 505942        67              6        11
2      Aaron Appindangoye 505942        67              6        11
3      Aaron Appindangoye 505942        62              6        11
4      Aaron Appindangoye 505942        61              5        10
5      Aaron Appindangoye 505942        61              5        10
6      Aaron Cresswell    155782        74             14         7
7      Aaron Cresswell    155782        74             14         7
8      Aaron Cresswell    155782        73             14         7
9      Aaron Cresswell    155782        73             14         7
10     Aaron Cresswell    155782        73             14         7
11     Aaron Cresswell    155782        73             14         7
12     Aaron Cresswell    155782        74             14         7
13     Aaron Cresswell    155782        73             14         7
14     Aaron Cresswell    155782        71             13         6
15     Aaron Cresswell    155782        71             13         6
16     Aaron Cresswell    155782        71             13         6
17     Aaron Cresswell    155782        70             13         6
18     Aaron Cresswell    155782        70             13         6
19     Aaron Cresswell    155782        70             13         6
20     Aaron Cresswell    155782        70             13         6
21     Aaron Cresswell    155782        70             13         6
22     Aaron Cresswell    155782        70             13         6
23     Aaron Cresswell    155782        69             13         6
24     Aaron Cresswell    155782        69             13         6
25     Aaron Cresswell    155782        69             13         6
26     Aaron Cresswell    155782        69             13         6
27     Aaron Cresswell    155782        69             13         6
28     Aaron Cresswell    155782        69             13         6
29     Aaron Cresswell    155782        69             13         6
30     Aaron Cresswell    155782        68             13         6
⋮      ⋮                  ⋮             ⋮              ⋮         ⋮
99971  Leandro Pimenta    185705        65             15         6
99972  Leandro Pimenta    185705        65             15         6
99973  Leandro Pimenta    185705        65             15         6
99974  Leandro Pimenta    185705        65             15         6
99975  Leandro Pimenta    185705        65             15         6
99976  Leandro Pimenta    185705        65             15         6
99977  Leandro Rinaudo     39569        65             12        15
99978  Leandro Rinaudo     39569        71             12        15
99979  Leandro Rinaudo     39569        71             12        15
99980  Leandro Rinaudo     39569        72             11        14
99981  Leandro Rinaudo     39569        72             11        14
99982  Leandro Rinaudo     39569        71             11        14
99983  Leandro Rinaudo     39569        71             11        14
99984  Leandro Rinaudo     39569        71             11        14
99985  Leandro Rinaudo     39569        71             11        14
99986  Leandro Rinaudo     39569        71             11        14
99987  Leandro Rinaudo     39569        71             11        14
99988  Leandro Rinaudo     39569        71             11        14
99989  Leandro Rinaudo     39569        71             11        14
99990  Leandro Rinaudo     39569        72             12        15
99991  Leandro Rinaudo     39569        72             12        15
99992  Leandro Rinaudo     39569        72             12        15
99993  Leandro Rinaudo     39569        72             12        15
99994  Leandro Rinaudo     39569        73             12        15
99995  Leandro Rinaudo     39569        71             12        15
99996  Leandro Rinaudo     39569        72             12        22
99997  Leandro Rinaudo     39569        73             12        22
99998  Leandro Rinaudo     39569        73             12        22
99999  Leandro Rinaudo     39569        56             12        22
100000 Leandro Rinaudo     39569        56             12        12
       gk_kicking gk_positioning gk_reflexes
1      10         8               8
2      10         8               8
3      10         8               8
4       9         7               7
5       9         7               7
6       9         9              12
7       9         9              12
8       9         9              12
9       9         9              12
10      9         9              12
11      9         9              12
12      9         9              12
13      9         9              12
14      8         8              11
15      8         8              11
16      8         8              11
17      8         8              11
18      8         8              11
19      8         8              11
20      8         8              11
21      8         8              11
22      8         8              11
23      8         8              11
24      8         8              11
25      8         8              11
26      8         8              11
27      8         8              11
28      8         8              11
29      8         8              11
30      8         8              11
⋮      ⋮          ⋮              ⋮
99971  10         13             10
99972  10         13             10
99973  10         13             10
99974  10         13             10
99975  10         13             10
99976  10         13             10
99977   9         15              5
99978   9         15              5
99979   9         15              5
99980   8         14              4
99981   8         14              4
99982   8         14              4
99983   8         14              4
99984   8         14              4
99985   8         14              4
99986   8         14              4
99987   8         14              4
99988   8         14              4
99989   8         14              4
99990   9         15              5
99991   9         15              5
99992   9         15              5
99993   9         15              5
99994   9         15              5
99995   9         15              5
99996  55         22             22
99997  55         22             22
99998  55         22             22
99999  46         22             22
100000 46          9             12

In [57]:
result <- p1 %>% 
             group_by(player_api_id) %>%
             #filter(!is.na(overall_rating))%>%
             filter(overall_rating == max(overall_rating))%>%
            select(player_name,overall_rating) %>%
              arrange(desc(overall_rating))
result<-unique(result)
head(unique(result),10)

Adding missing grouping variables: `player_api_id`

   player_api_id player_name       overall_rating
1  30981         Lionel Messi      94
2  30893         Cristiano Ronaldo 93
3  30717         Gianluigi Buffon  93
4  30829         Wayne Rooney      93
5  39989         Gregory Coupet    92
6  39854         Xavi Hernandez    92
7  30723         Alessandro Nesta  91
8  30955         Andres Iniesta    91
9  34520         Fabio Cannavaro   91
10 30657         Iker Casillas     91

In [58]:
result%>% filter(player_api_id==41097)

  player_api_id player_name      overall_rating
1 41097         Stephane Ruffier 83

In [59]:
r2 <- p1 %>% 
             group_by(player_api_id) %>%
             #filter(!is.na(gk_diving) | )%>%
             mutate(gk_all=gk_diving + gk_handling + gk_kicking + gk_positioning + gk_reflexes) %>%
             filter(gk_all == max(gk_all))%>%
             select(player_api_id,gk_all)%>%
              arrange(desc(gk_all)) 
          
r2<-unique(r2)
unique(r2)
#r2<-result%>%arrange(desc(gk_all))
#unique(r2)

      player_api_id gk_all
1      30717        449
2      39989        447
3      30859        445
4      30657        442
5      27299        440
6      30989        438
7      24503        437
8      30726        436
9     182917        429
10     30660        428
11     30622        426
12     26295        425
13     30742        425
14     32657        425
15     30841        424
16     27341        424
17     30648        423
18     33986        421
19     31293        421
20     30380        420
21     30713        419
22     24591        419
23     30974        418
24     41466        418
25     27424        418
26     24224        418
27     31465        418
28    215168        417
29     34530        417
30     26173        417
⋮     ⋮             ⋮
11031 192323        35
11032 214977        35
11033 361380        35
11034 526241        35
11035 214899        35
11036 243456        35
11037 202713        35
11038 591757        35
11039 111182        35
11040 528439        34
11041  46784        34
11042 689987        34
11043 245022        34
11044 355713        34
11045 239219        34
11046 265412        34
11047 299374        33
11048 145058        33
11049 674492        33
11050  71557        33
11051 215411        33
11052 459000        32
11053 705484        32
11054  69266        30
11055 200238        28
11056 265703        25
11057 245412        20
11058 280971        20
11059 212695        20
11060 164341        14

In [60]:
m

      id    country_id league_id season    stage date
1      1    1          1         2008/2009  1    2008-08-17 00:00:00
2      2    1          1         2008/2009  1    2008-08-16 00:00:00
3      3    1          1         2008/2009  1    2008-08-16 00:00:00
4      4    1          1         2008/2009  1    2008-08-17 00:00:00
5      5    1          1         2008/2009  1    2008-08-16 00:00:00
6      6    1          1         2008/2009  1    2008-09-24 00:00:00
7      7    1          1         2008/2009  1    2008-08-16 00:00:00
8      8    1          1         2008/2009  1    2008-08-16 00:00:00
9      9    1          1         2008/2009  1    2008-08-16 00:00:00
10    10    1          1         2008/2009 10    2008-11-01 00:00:00
11    11    1          1         2008/2009 10    2008-10-31 00:00:00
12    12    1          1         2008/2009 10    2008-11-02 00:00:00
13    13    1          1         2008/2009 10    2008-11-01 00:00:00
14    14    1          1         2008/2009 10    2008-11-01 00:00:00
15    15    1          1         2008/2009 10    2008-11-01 00:00:00
16    16    1          1         2008/2009 10    2008-11-01 00:00:00
17    17    1          1         2008/2009 10    2008-11-01 00:00:00
18    18    1          1         2008/2009 10    2008-11-02 00:00:00
19    19    1          1         2008/2009 11    2008-11-08 00:00:00
20    20    1          1         2008/2009 11    2008-11-08 00:00:00
21    21    1          1         2008/2009 11    2008-11-09 00:00:00
22    22    1          1         2008/2009 11    2008-11-07 00:00:00
23    23    1          1         2008/2009 11    2008-11-08 00:00:00
24    24    1          1         2008/2009 11    2008-11-08 00:00:00
25    25    1          1         2008/2009 11    2008-11-08 00:00:00
26    26    1          1         2008/2009 11    2008-11-08 00:00:00
27    27    1          1         2008/2009 11    2008-11-09 00:00:00
28    28    1          1         2008/2009 12    2008-11-16 00:00:00
29    29    1          1         2008/2009 12    2008-11-15 00:00:00
30    30    1          1         2008/2009 12    2008-11-15 00:00:00
⋮     ⋮     ⋮          ⋮         ⋮         ⋮     ⋮
25950 25950 24558      24558     2015/2016 4     2015-08-08 00:00:00
25951 25951 24558      24558     2015/2016 4     2015-08-08 00:00:00
25952 25952 24558      24558     2015/2016 4     2015-08-09 00:00:00
25953 25953 24558      24558     2015/2016 4     2015-08-09 00:00:00
25954 25954 24558      24558     2015/2016 4     2015-08-09 00:00:00
25955 25955 24558      24558     2015/2016 5     2015-08-12 00:00:00
25956 25956 24558      24558     2015/2016 5     2015-08-12 00:00:00
25957 25957 24558      24558     2015/2016 5     2015-08-12 00:00:00
25958 25958 24558      24558     2015/2016 5     2015-08-13 00:00:00
25959 25959 24558      24558     2015/2016 5     2015-08-13 00:00:00
25960 25960 24558      24558     2015/2016 6     2015-08-22 00:00:00
25961 25961 24558      24558     2015/2016 6     2015-08-23 00:00:00
25962 25962 24558      24558     2015/2016 6     2015-08-23 00:00:00
25963 25963 24558      24558     2015/2016 6     2015-08-23 00:00:00
25964 25964 24558      24558     2015/2016 6     2015-08-22 00:00:00
25965 25965 24558      24558     2015/2016 7     2015-08-29 00:00:00
25966 25966 24558      24558     2015/2016 7     2015-08-29 00:00:00
25967 25967 24558      24558     2015/2016 7     2015-08-30 00:00:00
25968 25968 24558      24558     2015/2016 7     2015-08-30 00:00:00
25969 25969 24558      24558     2015/2016 7     2015-08-30 00:00:00
25970 25970 24558      24558     2015/2016 8     2015-09-12 00:00:00
25971 25971 24558      24558     2015/2016 8     2015-09-12 00:00:00
25972 25972 24558      24558     2015/2016 8     2015-09-13 00:00:00
25973 25973 24558      24558     2015/2016 8     2015-09-13 00:00:00
25974 25974 24558      24558     2015/2016 8     2015-09-13 00:00:00
25975 25975 24558      24558     2015/2016 9     2015-09-22 00:00:00
25976 25976 24558      24558     2015/2016 9     2015-09-23 00:00:00
25977 25977 24558      24558     2015/2016 9     2015-09-23 00:00:00
25978 25978 24558      24558     2015/2016 9     2015-09-22 00:00:00
25979 25979 24558      24558     2015/2016 9     2015-09-23 00:00:00
      match_api_id home_team_api_id away_team_api_id home_team_goal ⋯ SJA VCH
1     492473        9987             9993            1              ⋯  4  1.65
2     492474       10000             9994            0              ⋯  3  2.00
3     492475        9984             8635            0              ⋯  2  2.35
4     492476        9991             9998            5              ⋯  7  1.45
5     492477        7947             9985            1              ⋯  1  4.50
6     492478        8203             8342            1              ⋯  1  4.35
7     492479        9999             8571            2              ⋯  3  2.10
8     492480        4049             9996            1              ⋯  2  2.80
9     492481       10001             9986            1              ⋯  3  2.25
10    492564        8342             8571            4              ⋯ 10  1.30
11    492565        9985             9986            1              ⋯ 10  1.28
12    492566       10000             9991            0              ⋯  2  2.65
13    492567        9994             9998            0              ⋯  4  2.00
14    492568        7947            10001            2              ⋯  2  2.75
15    492569        8203             9999            1              ⋯  4  1.70
16    492570        9996             9984            0              ⋯  2  2.20
17    492571        4049             9987            1              ⋯  1  5.50
18    492572        9993             8635            1              ⋯  1  3.60
19    492573        8635             9994            2              ⋯  9  1.28
20    492574        9998             9996            0              ⋯  2  2.35
21    492575        9986             8342            2              ⋯  2  3.25
22    492576        9984            10000            2              ⋯  4  1.75
23    492577        9991             7947            1              ⋯  7  1.35
24    492578        9999             4049            1              ⋯  4  1.80
25    492579        8571             8203            0              ⋯  3  2.00
26    492580       10001             9987            1              ⋯  2  2.40
27    492581        9993             9985            1              ⋯  1  3.75
28    492582        8342             8635            1              ⋯  3  2.25
29    492583        9987             9999            1              ⋯ 10  1.25
30    492584       10000             9993            2              ⋯  3  2.10
⋮     ⋮            ⋮                ⋮                ⋮              ⋱ ⋮   ⋮
25950 1992066       9956             7896            6              ⋯ NA  NA
25951 1992067      10199             9931            1              ⋯ NA  NA
25952 1992068      10190            10243            0              ⋯ NA  NA
25953 1992069       9824            10179            1              ⋯ NA  NA
25954 1992070      10192            10191            3              ⋯ NA  NA
25955 1992071       9931            10191            3              ⋯ NA  NA
25956 1992072      10192             7896            0              ⋯ NA  NA
25957 1992073      10199            10190            0              ⋯ NA  NA
25958 1992074      10179            10243            3              ⋯ NA  NA
25959 1992075       9824             9956            3              ⋯ NA  NA
25960 1992076       7896             9931            1              ⋯ NA  NA
25961 1992077      10179            10192            1              ⋯ NA  NA
25962 1992078      10190             9956            0              ⋯ NA  NA
25963 1992079      10191             9824            1              ⋯ NA  NA
25964 1992080      10243            10199            2              ⋯ NA  NA
25965 1992081       7896            10199            0              ⋯ NA  NA
25966 1992082       9824            10190            1              ⋯ NA  NA
25967 1992083      10191            10179            0              ⋯ NA  NA
25968 1992084       9931            10243            3              ⋯ NA  NA
25969 1992085       9956            10192            3              ⋯ NA  NA
25970 1992086       9931            10190            2              ⋯ NA  NA
25971 1992087      10192             9824            4              ⋯ NA  NA
25972 1992088      10199             9956            3              ⋯ NA  NA
25973 1992089      10243            10191            3              ⋯ NA  NA
25974 1992090      10179             7896            3              ⋯ NA  NA
25975 1992091      10190            10191            1              ⋯ NA  NA
25976 1992092       9824            10199            1              ⋯ NA  NA
25977 1992093       9956            10179            2              ⋯ NA  NA
25978 1992094       7896            10243            0              ⋯ NA  NA
25979 1992095      10192             9931            4              ⋯ NA  NA
      VCD  VCA  GBH  GBD  GBA BSH  BSD  BSA
1     3.40 4.50 1.78 3.25  4  1.73 3.40 4.20
2     3.25 3.25 1.85 3.25  3  1.91 3.25 3.60
3     3.25 2.65 2.50 3.20  2  2.30 3.20 2.75
4     3.75 6.50 1.50 3.75  5  1.44 3.75 6.50
5     3.40 1.65 4.50 3.50  1  4.75 3.30 1.67
6     3.40 1.70 4.50 3.40  1    NA   NA   NA
7     3.25 3.00 1.85 3.25  3  2.10 3.25 3.10
8     3.25 2.25 2.80 3.20  2  2.88 3.25 2.20
9     3.25 2.80 2.20 3.30  2  2.25 3.20 2.80
10    4.35 8.50 1.25 5.00 10  1.29 4.50 9.00
11    4.50 8.50 1.25 5.00 10  1.25 5.00 9.00
12    3.30 2.30 2.60 3.25  2  2.62 3.20 2.38
13    3.20 3.40 1.85 3.30  4  1.83 3.30 3.80
14    3.20 2.30 2.75 3.25  2  2.75 3.20 2.30
15    3.40 4.35 1.75 3.40  4  1.70 3.40 4.33
16    3.25 2.90 2.30 3.25  2  2.30 3.20 2.75
17    3.50 1.55 5.25 3.60  1  6.00 3.60 1.50
18    3.25 1.90 4.10 3.40  1  3.80 3.30 1.83
19    4.50 8.50 1.30 4.75  7  1.30 4.50 8.50
20    3.25 2.65 2.30 3.20  2  2.30 3.25 2.70
21    3.25 2.00 3.10 3.20  2  3.10 3.25 2.10
22    3.25 4.35 1.80 3.30  4  1.70 3.30 4.50
23    4.00 7.50 1.40 4.20  7  1.36 4.20 7.00
24    3.25 4.00 1.85 3.30  4  1.80 3.30 4.00
25    3.25 3.25 1.95 3.20  3  2.00 3.25 3.30
26    3.25 2.60 2.50 3.25  2  2.50 3.20 2.50
27    3.25 1.85 3.60 3.25  1  3.50 3.30 1.91
28    3.10 2.80 2.10 3.20  3  2.20 3.20 2.90
29    5.00 9.00 1.27 5.00  8  1.25 5.00 9.00
30    3.30 3.10 2.00 3.20  3  2.00 3.25 3.30
⋮     ⋮    ⋮    ⋮    ⋮    ⋮   ⋮    ⋮    ⋮
25950 NA   NA   NA   NA   NA  NA   NA   NA
25951 NA   NA   NA   NA   NA  NA   NA   NA
25952 NA   NA   NA   NA   NA  NA   NA   NA
25953 NA   NA   NA   NA   NA  NA   NA   NA
25954 NA   NA   NA   NA   NA  NA   NA   NA
25955 NA   NA   NA   NA   NA  NA   NA   NA
25956 NA   NA   NA   NA   NA  NA   NA   NA
25957 NA   NA   NA   NA   NA  NA   NA   NA
25958 NA   NA   NA   NA   NA  NA   NA   NA
25959 NA   NA   NA   NA   NA  NA   NA   NA
25960 NA   NA   NA   NA   NA  NA   NA   NA
25961 NA   NA   NA   NA   NA  NA   NA   NA
25962 NA   NA   NA   NA   NA  NA   NA   NA
25963 NA   NA   NA   NA   NA  NA   NA   NA
25964 NA   NA   NA   NA   NA  NA   NA   NA
25965 NA   NA   NA   NA   NA  NA   NA   NA
25966 NA   NA   NA   NA   NA  NA   NA   NA
25967 NA   NA   NA   NA   NA  NA   NA   NA
25968 NA   NA   NA   NA   NA  NA   NA   NA
25969 NA   NA   NA   NA   NA  NA   NA   NA
25970 NA   NA   NA   NA   NA  NA   NA   NA
25971 NA   NA   NA   NA   NA  NA   NA   NA
25972 NA   NA   NA   NA   NA  NA   NA   NA
25973 NA   NA   NA   NA   NA  NA   NA   NA
25974 NA   NA   NA   NA   NA  NA   NA   NA
25975 NA   NA   NA   NA   NA  NA   NA   NA
25976 NA   NA   NA   NA   NA  NA   NA   NA
25977 NA   NA   NA   NA   NA  NA   NA   NA
25978 NA   NA   NA   NA   NA  NA   NA   NA
25979 NA   NA   NA   NA   NA  NA   NA   NA

In [61]:
h1<-m%>%group_by(home_player_1)%>% summarize(NoOfOccurances=n() )
h2<-m%>%group_by(home_player_2)%>% summarize(NoOfOccurances=n() )
h3<-m%>%group_by(home_player_3)%>% summarize(NoOfOccurances=n() )
h4<-m%>%group_by(home_player_4)%>% summarize(NoOfOccurances=n() )
h5<-m%>%group_by(home_player_5)%>% summarize(NoOfOccurances=n() )
h6<-m%>%group_by(home_player_6)%>% summarize(NoOfOccurances=n() )
h7<-m%>%group_by(home_player_7)%>% summarize(NoOfOccurances=n() )
h8<-m%>%group_by(home_player_8)%>% summarize(NoOfOccurances=n() )
h9<-m%>%group_by(home_player_9)%>% summarize(NoOfOccurances=n() )
h10<-m%>%group_by(home_player_10)%>% summarize(NoOfOccurances=n() )
h11<-m%>%group_by(home_player_11)%>% summarize(NoOfOccurances=n() )
a1<-m%>%group_by(away_player_1)%>% summarize(NoOfOccurances=n() )
a2<-m%>%group_by(away_player_2)%>% summarize(NoOfOccurances=n() )
a3<-m%>%group_by(away_player_3)%>% summarize(NoOfOccurances=n() )
a4<-m%>%group_by(away_player_4)%>% summarize(NoOfOccurances=n() )
a5<-m%>%group_by(away_player_5)%>% summarize(NoOfOccurances=n() )
a6<-m%>%group_by(away_player_6)%>% summarize(NoOfOccurances=n() )
a7<-m%>%group_by(away_player_7)%>% summarize(NoOfOccurances=n() )
a8<-m%>%group_by(away_player_8)%>% summarize(NoOfOccurances=n() )
a9<-m%>%group_by(away_player_9)%>% summarize(NoOfOccurances=n() )
a10<-m%>%group_by(away_player_10)%>% summarize(NoOfOccurances=n() )
a11<-m%>%group_by(away_player_11)%>% summarize(NoOfOccurances=n() )

class(h1)

[1] "tbl_df"     "tbl"        "data.frame"

In [62]:
names(h1)[names(h1)=="home_player_1"] <- "player_api_id"
names(h2)[names(h2)=="home_player_2"] <- "player_api_id"
names(h3)[names(h3)=="home_player_3"] <- "player_api_id"
names(h4)[names(h4)=="home_player_4"] <- "player_api_id"
names(h5)[names(h5)=="home_player_5"] <- "player_api_id"
names(h6)[names(h6)=="home_player_6"] <- "player_api_id"
names(h7)[names(h7)=="home_player_7"] <- "player_api_id"
names(h8)[names(h8)=="home_player_8"] <- "player_api_id"
names(h9)[names(h9)=="home_player_9"] <- "player_api_id"
names(h10)[names(h10)=="home_player_10"] <- "player_api_id"
names(h11)[names(h11)=="home_player_11"] <- "player_api_id"
names(a1)[names(a1)=="away_player_1"] <- "player_api_id"
names(a2)[names(a2)=="away_player_2"] <- "player_api_id"
names(a3)[names(a3)=="away_player_3"] <- "player_api_id"
names(a4)[names(a4)=="away_player_4"] <- "player_api_id"
names(a5)[names(a5)=="away_player_5"] <- "player_api_id"
names(a6)[names(a6)=="away_player_6"] <- "player_api_id"
names(a7)[names(a7)=="away_player_7"] <- "player_api_id"
names(a8)[names(a8)=="away_player_8"] <- "player_api_id"
names(a9)[names(a9)=="away_player_9"] <- "player_api_id"
names(a10)[names(a10)=="away_player_10"] <- "player_api_id"
names(a11)[names(a11)=="away_player_11"] <- "player_api_id"


occurances<-rbind(h1,h2,h3,h4,h5,h6,h7,h8,h9,h10,h11,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,all=TRUE)
occurances<-na.omit(occurances)
occurances
#occurances%>% arrange( desc(NoOfOccurances)) %>%group_by(player_api_id)

      player_api_id NoOfOccurances
1      2984          19
2      5044          11
3      5047           5
4      5440           3
5      5710          27
6      7334           6
7      7621          27
8      9183          17
9     10637         110
10    11024          70
11    11316          23
12    11319          90
13    11320          48
14    11321          28
15    11336          36
16    11498           1
17    11716           1
18    11760           2
19    12209           4
20    12318          54
21    12340          34
22    13033          41
23    13034           4
24    13131          35
25    13320          36
26    13345          72
27    13390          29
28    13436          60
29    13454          48
30    13471          74
⋮     ⋮             ⋮
67474 637753        1
67475 638029        2
67476 639150        1
67477 643229        1
67478 643982        1
67479 644002        1
67480 645704        2
67481 658657        2
67482 659463        1
67483 660165        1
67484 661884        2
67485 661902        2
67486 666957        1
67487 667951        4
67488 668820        3
67489 671159        2
67490 671331        3
67491 678234        2
67492 684978        2
67493 687687        1
67494 688295        1
67495 690188        1
67496 690364        1
67497 692984        1
67498 696365        4
67499 717270        1
67500 717557        3
67501 725718        1
67502 726956        3
67503      1        1

In [63]:
player

      player_name            player_api_id
1     Aaron Appindangoye     505942
2     Aaron Cresswell        155782
3     Aaron Doran            162549
4     Aaron Galindo           30572
5     Aaron Hughes            23780
6     Aaron Hunt              27316
7     Aaron Kuhl             564793
8     Aaron Lennon            30895
9     Aaron Lennox           528212
10    Aaron Meijers          101042
11    Aaron Mokoena           23889
12    Aaron Mooy             231592
13    Aaron Muirhead         163222
14    Aaron Niguez            40719
15    Aaron Ramsey            75489
16    Aaron Splaine          597948
17    Aaron Taylor-Sinclair  161644
18    Aaron Wilbraham         23499
19    Aatif Chahechouhe      120919
20    Abasse Ba               46447
21    Abdelaziz Barrada      167027
22    Abdelfettah Boukhriss  245653
23    Abdelhamid El Kaoutari 128456
24    Abdelkader Ghezzal      42664
25    Abdellah Zoubir        425950
26    Abdelmajid Oulmers      38423
27    Abdelmalek Cherrad       3264
28    Abdelmalek El Hasnaoui 467485
29    Abdelouahed Chakhsi    306735
30    Abderrazak Jadid        41659
⋮     ⋮                      ⋮
11031 Zezinho                244155
11032 Zhi Zheng               19696
11033 Zhi-Gin Lam            290868
11034 Zie Diabate            169594
11035 Ziggy Gordon           244953
11036 Ziguy Badibanga        200607
11037 Zinedine Machach       642618
11038 Zinho Gano             277772
11039 Ziri Hammar            246332
11040 Zizo                   532766
11041 Zlatan Bajramovic       27305
11042 Zlatan Ibrahimovic      35724
11043 Zlatan Ljubijankic      12574
11044 Zlatko Dedic            39494
11045 Zlatko Janjic           17233
11046 Zlatko Junuzovic        42860
11047 Zola Matumona           37128
11048 Zoltan Gera             24737
11049 Zoltan Stieber         107281
11050 Zoltan Szelesi          39801
11051 Zoran Josipovic        491794
11052 Zoran Rendulic          56929
11053 Zoran Tosic             99031
11054 Zouhaier Dhaouadhi     192132
11055 Zouhair Feddal         282473
11056 Zoumana Camara          26357
11057 Zsolt Laczko           111182
11058 Zsolt Low               36491
11059 Zurab Khizanishvili     35506
11060 Zvjezdan Misimovic      39902

In [64]:
#count(m,home_player_1)
appearances<-aggregate(NoOfOccurances~., occurances, FUN=sum)%>%  arrange( desc(NoOfOccurances))#%>% select(team_long_name,NoOfOccurances)
appearances
#player
final <- merge(appearances,result,by='player_api_id') %>%  arrange( desc(NoOfOccurances))
final<-unique(final)
#appearances.outer_join(result)

      player_api_id NoOfOccurances
1     31293         300
2     41097         294
3     33764         286
4     42422         286
5     26295         282
6     31465         282
7     31432         275
8     26168         268
9     26399         262
10    94550         260
11    30893         259
12    23782         258
13    38433         257
14    41658         257
15    27299         255
16    32575         254
17    23792         253
18    40695         253
19    42276         253
20    56678         252
21    24846         251
22    30859         251
23    38424         250
24    30660         249
25    30981         249
26    32569         248
27    39477         247
28    41466         247
29    30907         245
30    34447         245
⋮     ⋮             ⋮
11032 661509        1
11033 662818        1
11034 664961        1
11035 667786        1
11036 667952        1
11037 667964        1
11038 667970        1
11039 670927        1
11040 671518        1
11041 674492        1
11042 675088        1
11043 680031        1
11044 684723        1
11045 687572        1
11046 689987        1
11047 690290        1
11048 703659        1
11049 710807        1
11050 715642        1
11051 716998        1
11052 717270        1
11053 725718        1
11054 728414        1
11055 728478        1
11056 730065        1
11057 742405        1
11058 743720        1
11059 744907        1
11060 750435        1
11061 750584        1

In [65]:
s1=tbl(my_db, sql("SELECT home_player_1 as player_api_id, count(*) as NumberofLeagues  from (SELECT league_id , home_player_1 from Match where home_player_1  UNION
                   SELECT league_id , home_player_2 from Match  where home_player_2  UNION
SELECT league_id , home_player_3 from Match where home_player_3  UNION
SELECT league_id , home_player_4 from Match where home_player_4  UNION
SELECT league_id , home_player_5 from Match where home_player_5  UNION
SELECT league_id , home_player_6 from Match where home_player_6   UNION
SELECT league_id , home_player_7 from Match where home_player_7  UNION
SELECT league_id , home_player_8 from Match where home_player_8   UNION
SELECT league_id , home_player_9 from Match where home_player_9   UNION
SELECT league_id , home_player_10 from Match  where home_player_10  UNION
SELECT league_id , home_player_11 from Match where home_player_11   UNION
SELECT league_id , away_player_1 from Match where away_player_1    UNION
SELECT league_id , away_player_2 from Match where away_player_2   UNION
SELECT league_id , away_player_3 from Match where away_player_3   UNION
SELECT league_id , away_player_4 from Match where away_player_4   UNION
SELECT league_id , away_player_5 from Match where away_player_5   UNION
SELECT league_id , away_player_6 from Match where away_player_6   UNION
SELECT league_id , away_player_7 from Match where away_player_7   UNION
SELECT league_id , away_player_8 from Match where away_player_8   UNION
SELECT league_id , away_player_9 from Match where away_player_9   UNION
SELECT league_id , away_player_10 from Match where away_player_10   UNION 
SELECT league_id , away_player_11 from Match)  GROUP BY home_player_1  HAVING home_player_1 NOT LIKE('NA') ORDER BY count(*) DESC"))
collect(s1)
final1 <- merge(final,s1,by="player_api_id")

#final2<-merge(final1,result,by='player_api_id')

      player_api_id NumberofLeagues
1      42119        6
2     116750        5
3     178538        5
4      22543        4
5      24123        4
6      25816        4
7      26434        4
8      26489        4
9      26675        4
10     30477        4
11     30692        4
12     30841        4
13     30890        4
14     30918        4
15     31294        4
16     31300        4
17     32937        4
18     33074        4
19     36784        4
20     38229        4
21     38369        4
22     38700        4
23     38795        4
24     40004        4
25     40165        4
26     41877        4
27     46509        4
28     47547        4
29     71353        4
30     93484        4
⋮     ⋮             ⋮
11031 701154        1
11032 703659        1
11033 704523        1
11034 705484        1
11035 706985        1
11036 710807        1
11037 715642        1
11038 716998        1
11039 717248        1
11040 717270        1
11041 717557        1
11042 719413        1
11043 720738        1
11044 721133        1
11045 722766        1
11046 723037        1
11047 725718        1
11048 726956        1
11049 728125        1
11050 728414        1
11051 728478        1
11052 730065        1
11053 733787        1
11054 742405        1
11055 743720        1
11056 744907        1
11057 746419        1
11058 748432        1
11059 750435        1
11060 750584        1

In [66]:
final1

      player_api_id NoOfOccurances player_name              overall_rating
1     2625           90            Patryk Rachwal,18        63
2     2752           81            Diego Mainz              72
3     2768           71            Jose Dorado              75
4     2770           16            Ignacio Gonzalez         74
5     2790           50            Alberto Rey              73
6     2796            1            Javier Jimenez           69
7     2802          144            Pablo Hernandez          82
8     2805          131            Ruben Perez              76
9     2857            3            Ivan Perez               72
10    2862           17            Vicente Sanchez          76
11    2907            6            Gregory Lacombe          68
12    2973           16            Ugur Inceman             72
13    2977            5            David Rivas Rodriguez    82
14    2983           71            Jorge Molina             75
15    2984           38            Sergio Aragones          75
16    3140           42            Alexandre Hauw           69
17    3204           42            Marat Izmailov           81
18    3263           19            Kelly Berville           67
19    3264            1            Abdelmalek Cherrad       62
20    3316            6            Oscar Sanchez            71
21    3329           85            Vincent Euvrard          64
22    3377            1            Luca Belingheri          72
23    3441           74            Aleksander Radosavljevic 71
24    3512            4            Peter Halmosi            75
25    3517           17            Alexandr Kerzhakov       82
26    3520           70            Andrey Arshavin          86
27    4747           36            Lee Wilkie               73
28    4863           25            Boban Grncarov           66
29    4902           68            Iriney                   77
30    4939           97            Tim Clancy               64
⋮     ⋮             ⋮              ⋮                        ⋮
11031 701154         2             Kylian Mbappe Lottin     65
11032 703659         1             Colin Trachsel           51
11033 704523         4             Christopher Nkunku       62
11034 705484         4             Eray Cumart              52
11035 706985         2             Jordan Lyden             58
11036 710807         1             Jonatan Montiel          67
11037 715642         1             Aissa Laidouni           59
11038 716998         1             Sebastien Lamonge        56
11039 717248         4             Felipe Augusto           64
11040 717270         1             Antoine Rabillard        61
11041 717557         4             Levi Garcia              64
11042 719413         3             Dorian Caddy             64
11043 720738         5             Charles Traore           55
11044 721133        15             Rafa Soares              70
11045 722766        13             Charly Musonda           71
11046 723037         7             Wanderson Lima           53
11047 725718         1             Dennis van der Heijden   60
11048 726956         4             Cedric Itten             54
11049 728125         2             Christopher McLaughlin   50
11050 728414         1             Justin Hoogma            59
11051 728478         1             Kamil Jozwiak            56
11052 730065         1             Jorge Intima             57
11053 733787         2             Linus Obexer             51
11054 742405         1             Tom Davies               51
11055 743720         1             Charles Pickel           50
11056 744907         1             Greg Taylor              53
11057 746419         2             Francisco Afonso         59
11058 748432         2             Fynn Arkenberg           58
11059 750435         1             Rees Greenwood           60
11060 750584         1             Alexandre Azevedo        58
      NumberofLeagues
1     1
2     1
3     1
4     2
5     1
6     1
7     2
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
30    1
⋮     ⋮
11031 1
11032 1
11033 1
11034 1
11035 1
11036 1
11037 1
11038 1
11039 1
11040 1
11041 1
11042 1
11043 1
11044 1
11045 1
11046 1
11047 1
11048 1
11049 1
11050 1
11051 1
11052 1
11053 1
11054 1
11055 1
11056 1
11057 1
11058 1
11059 1
11060 1

In [67]:
final2<-merge(final1,r2,by="player_api_id")

 # Writing Player.csv

In [68]:
final2
write.csv(final2,file="player.csv")

      player_api_id NoOfOccurances player_name              overall_rating
1     2625           90            Patryk Rachwal,18        63
2     2752           81            Diego Mainz              72
3     2768           71            Jose Dorado              75
4     2770           16            Ignacio Gonzalez         74
5     2790           50            Alberto Rey              73
6     2796            1            Javier Jimenez           69
7     2802          144            Pablo Hernandez          82
8     2805          131            Ruben Perez              76
9     2857            3            Ivan Perez               72
10    2862           17            Vicente Sanchez          76
11    2907            6            Gregory Lacombe          68
12    2973           16            Ugur Inceman             72
13    2977            5            David Rivas Rodriguez    82
14    2983           71            Jorge Molina             75
15    2984           38            Sergio Aragones          75
16    3140           42            Alexandre Hauw           69
17    3204           42            Marat Izmailov           81
18    3263           19            Kelly Berville           67
19    3264            1            Abdelmalek Cherrad       62
20    3316            6            Oscar Sanchez            71
21    3329           85            Vincent Euvrard          64
22    3377            1            Luca Belingheri          72
23    3441           74            Aleksander Radosavljevic 71
24    3512            4            Peter Halmosi            75
25    3517           17            Alexandr Kerzhakov       82
26    3520           70            Andrey Arshavin          86
27    4747           36            Lee Wilkie               73
28    4863           25            Boban Grncarov           66
29    4902           68            Iriney                   77
30    4939           97            Tim Clancy               64
⋮     ⋮             ⋮              ⋮                        ⋮
11031 701154         2             Kylian Mbappe Lottin     65
11032 703659         1             Colin Trachsel           51
11033 704523         4             Christopher Nkunku       62
11034 705484         4             Eray Cumart              52
11035 706985         2             Jordan Lyden             58
11036 710807         1             Jonatan Montiel          67
11037 715642         1             Aissa Laidouni           59
11038 716998         1             Sebastien Lamonge        56
11039 717248         4             Felipe Augusto           64
11040 717270         1             Antoine Rabillard        61
11041 717557         4             Levi Garcia              64
11042 719413         3             Dorian Caddy             64
11043 720738         5             Charles Traore           55
11044 721133        15             Rafa Soares              70
11045 722766        13             Charly Musonda           71
11046 723037         7             Wanderson Lima           53
11047 725718         1             Dennis van der Heijden   60
11048 726956         4             Cedric Itten             54
11049 728125         2             Christopher McLaughlin   50
11050 728414         1             Justin Hoogma            59
11051 728478         1             Kamil Jozwiak            56
11052 730065         1             Jorge Intima             57
11053 733787         2             Linus Obexer             51
11054 742405         1             Tom Davies               51
11055 743720         1             Charles Pickel           50
11056 744907         1             Greg Taylor              53
11057 746419         2             Francisco Afonso         59
11058 748432         2             Fynn Arkenberg           58
11059 750435         1             Rees Greenwood           60
11060 750584         1             Alexandre Azevedo        58
      NumberofLeagues gk_all
1     1               153
2     1                53
3     1               128
4     2               148
5     1               144
6     1               340
7     2               146
8     1               141
9     1               143
10    1               146
11    1               135
12    1               147
13    1               104
14    1               139
15    1               364
16    1               136
17    1               156
18    1               115
19    1                98
20    1               108
21    1               130
22    1               138
23    1               138
24    1               143
25    1               149
26    1               159
27    1               128
28    1                54
29    1               145
30    1               116
⋮     ⋮               ⋮
11031 1               42
11032 1               48
11033 1               43
11034 1               32
11035 1               53
11036 1               47
11037 1               61
11038 1               46
11039 1               59
11040 1               56
11041 1               49
11042 1               54
11043 1               52
11044 1               60
11045 1               36
11046 1               54
11047 1               54
11048 1               41
11049 1               49
11050 1               54
11051 1               54
11052 1               59
11053 1               45
11054 1               56
11055 1               53
11056 1               57
11057 1               42
11058 1               46
11059 1               48
11060 1               54

# Reading Team Table

In [69]:
p6=tbl(my_db, sql("SELECT  team_long_name ,team.team_api_id , 
COALESCE(buildUpPlaySpeed,0) + COALESCE(buildUpPlayDribbling,0)+ COALESCE( buildUpPlayPassing,0) as BuildUpAll, 
COALESCE(chanceCreationPassing,0) + COALESCE(chanceCreationCrossing,0)+ COALESCE(chanceCreationShooting ,0) as ChanceUpAll,
COALESCE(defencePressure,0) + COALESCE(defenceAggression,0)+ COALESCE(defenceTeamWidth,0) as DefUpAll
                    from Team , Team_Attributes 
                    where Team.team_api_id=Team_Attributes.team_api_id  "))
collect(p6)

p6<-as.data.frame(p6)
p6[is.na(p6)] <- 0

     team_long_name       team_api_id BuildUpAll ChanceUpAll DefUpAll
1    FC Aarau              9930       110        180         150
2    FC Aarau              9930       156        181         145
3    FC Aarau              9930       142        181         145
4    Aberdeen              8485       140        210         200
5    Aberdeen              8485        99        153         146
6    Aberdeen              8485       120        170         140
7    Aberdeen              8485       107        145         144
8    Aberdeen              8485       184        181         143
9    Aberdeen              8485       176        186         157
10   AC Ajaccio            8576       100        135         130
11   AC Ajaccio            8576       110        180         140
12   AC Ajaccio            8576       111        134         138
13   AC Ajaccio            8576       111        134         138
14   AC Ajaccio            8576       168        138         138
15   AC Ajaccio            8576       168        138         138
16   Milan                 8564        75        170         125
17   Milan                 8564       115        160         150
18   Milan                 8564        95        135         140
19   Milan                 8564       102        168         150
20   Milan                 8564       170        177         164
21   Milan                 8564       170        171         164
22   Académica de Coimbra 10215        60        165          90
23   Académica de Coimbra 10215        80        155         140
24   Académica de Coimbra 10215        89        172         151
25   Académica de Coimbra 10215        89        172         151
26   Académica de Coimbra 10215       149        166         138
27   Académica de Coimbra 10215       150        166         138
28   ADO Den Haag         10217        65        145          90
29   ADO Den Haag         10217       106        181         173
30   ADO Den Haag         10217        82        159         170
⋮    ⋮                    ⋮           ⋮          ⋮           ⋮
1429 Neuchâtel Xamax       7955        99        121         116
1430 Xerez Club Deportivo  9868        60        150         140
1431 Xerez Club Deportivo  9868        98        159         165
1432 Xerez Club Deportivo  9868       104        138         153
1433 Xerez Club Deportivo  9868       104        138         153
1434 BSC Young Boys       10192       110        185         170
1435 BSC Young Boys       10192       117        202         158
1436 BSC Young Boys       10192       121        155         128
1437 BSC Young Boys       10192       121        155         128
1438 BSC Young Boys       10192       172        151         128
1439 BSC Young Boys       10192       172        151         128
1440 Zagłębie Lubin        8021       115        140         210
1441 Zagłębie Lubin        8021        91        123         157
1442 Zagłębie Lubin        8021        71        192         157
1443 Zagłębie Lubin        8021        71        167         157
1444 Zagłębie Lubin        8021       133        149         148
1445 Real Zaragoza         8394        60        155         115
1446 Real Zaragoza         8394        83        126         131
1447 Real Zaragoza         8394        57        166         158
1448 Real Zaragoza         8394        61        166         158
1449 Real Zaragoza         8394       121        166         158
1450 Real Zaragoza         8394       154        165         140
1451 Zawisza Bydgoszcz     8027       145        168         143
1452 Zawisza Bydgoszcz     8027       145        147         143
1453 SV Zulte-Waregem     10000       125        150         200
1454 SV Zulte-Waregem     10000       104        153         147
1455 SV Zulte-Waregem     10000       105        149         152
1456 SV Zulte-Waregem     10000       105        131         139
1457 SV Zulte-Waregem     10000       147        131         139
1458 SV Zulte-Waregem     10000       147        131         139

In [70]:
team <- p6 %>% 
             group_by(team_api_id) %>%
            filter(BuildUpAll == max(BuildUpAll))%>%
              select(team_long_name,BuildUpAll) %>%
              arrange(desc(BuildUpAll))

head(unique(team),10)

Adding missing grouping variables: `team_api_id`

   team_api_id team_long_name             BuildUpAll
1    9804      Torino                     209
2    8600      Udinese                    205
3    8194      Fortuna Düsseldorf         198
4    8033      Podbeskidzie Bielsko-Biała 193
5    8245      Korona Kielce              192
6  208931      Carpi                      190
7    8244      Widzew Łódź                190
8    8024      Widzew Łódź                190
9    9830      FC Nantes                  189
10   8543      Lazio                      188

In [71]:
team1 <- p6 %>% 
             group_by(team_api_id) %>%
            filter(ChanceUpAll == max(ChanceUpAll))%>%
              select(team_long_name,ChanceUpAll) %>%
              arrange(desc(ChanceUpAll))

head(unique(team1),10)

Adding missing grouping variables: `team_api_id`

   team_api_id team_long_name      ChanceUpAll
1  8543        Lazio               220
2  8697        SV Werder Bremen    216
3  9875        Napoli              215
4  8485        Aberdeen            210
5  8178        Bayer 04 Leverkusen 210
6  8658        Birmingham City     210
7  8191        Burnley             210
8  8344        Cardiff City        210
9  9860        Heart of Midlothian 210
10 8456        Manchester City     210

In [72]:
team3 <- p6 %>% 
             group_by(team_api_id) %>%
            filter(DefUpAll == max(DefUpAll))%>%
              select(team_long_name,DefUpAll) %>%
              arrange(desc(DefUpAll))

head(unique(team3),10)

Adding missing grouping variables: `team_api_id`

   team_api_id team_long_name        DefUpAll
1  9993        Beerschot AC          210
2  8658        Birmingham City       210
3  8483        Blackpool             210
4  8678        Bournemouth           210
5  8521        Stade Brestois 29     210
6  8344        Cardiff City          210
7  9904        Hannover 96           210
8  8667        Hull City             210
9  1957        Jagiellonia Białystok 210
10 8350        1. FC Kaiserslautern  210

In [73]:
p7=tbl(my_db, sql("SELECT home_team_api_id,sum(home_team_goal) from match group by home_team_api_id"))
collect(p7)
p8=tbl(my_db, sql("SELECT away_team_api_id,sum(away_team_goal) from match group by away_team_api_id"))
collect(p8)
p7<-as.data.frame(p7)
p8<-as.data.frame(p8)
p7[is.na(p7)] <- 0
p7[is.na(p8)] <- 0
names(p7)[names(p7)=="home_team_api_id"] <- "team_api_id"
names(p8)[names(p8)=="away_team_api_id"] <- "team_api_id"
names(p7)[names(p7)=="sum(home_team_goal)"] <- "GoalTotal"
names(p8)[names(p8)=="sum(away_team_goal)"] <- "GoalTotal"

p9=rbind(p7,p8,all=TRUE)
#p9
NumberOfGoals<-aggregate(GoalTotal~., p9, FUN=sum)%>%  arrange( desc(GoalTotal))
#NumberOfGoals

    home_team_api_id sum(home_team_goal)
1   1601             148
2   1773              74
3   1957             176
4   2033              70
5   2182             215
6   2183              96
7   2186             144
8   4049              22
9   4064              13
10  4087             105
11  4170              19
12  6269              19
13  6351              15
14  6367              19
15  6391              23
16  6403             166
17  6413             124
18  6421              35
19  6433              41
20  6493              74
21  6547              17
22  6601              27
23  6631              15
24  7730              52
25  7788              67
26  7794             101
27  7819             109
28  7841             131
29  7842              96
30  7844             156
⋮   ⋮                ⋮
270  10214           187
271  10215           136
272  10217           204
273  10218            90
274  10219            92
275  10228           267
276  10229           279
277  10233           249
278  10235           291
279  10238           135
280  10242            38
281  10243           241
282  10249           193
283  10251           136
284  10252           179
285  10260           338
286  10261           199
287  10264           239
288  10265           168
289  10267           299
290  10268            32
291  10269           219
292  10278            27
293  10281            94
294 108893            14
295 158085            56
296 177361            21
297 188163            15
298 208931            23
299 274581            41

    away_team_api_id sum(away_team_goal)
1   1601             132
2   1773              52
3   1957             111
4   2033              68
5   2182             157
6   2183              88
7   2186              91
8   4049              13
9   4064              14
10  4087              75
11  4170              12
12  6269              15
13  6351              13
14  6367               8
15  6391              14
16  6403             126
17  6413              80
18  6421              20
19  6433              33
20  6493              54
21  6547              12
22  6601              11
23  6631               9
24  7730              47
25  7788              52
26  7794              64
27  7819             111
28  7841             117
29  7842              71
30  7844             144
⋮   ⋮                ⋮
270  10214           145
271  10215           104
272  10217           162
273  10218            64
274  10219            61
275  10228           203
276  10229           213
277  10233           143
278  10235           198
279  10238           103
280  10242            33
281  10243           227
282  10249           151
283  10251           123
284  10252           156
285  10260           244
286  10261           125
287  10264           159
288  10265           164
289  10267           185
290  10268            33
291  10269           196
292  10278             9
293  10281            76
294 108893             7
295 158085            45
296 177361            12
297 188163            19
298 208931            14
299 274581            30

In [74]:
NumberOfGoals

    team_api_id GoalTotal
1    8634       849
2    8633       843
3    9925       695
4    9823       653
5    8640       652
6    8593       647
7    9931       619
8    8456       606
9    8455       583
10  10260       582
11   9825       573
12   9772       568
13   9847       568
14   9789       551
15   9885       543
16   9773       541
17   8650       531
18   8686       530
19  10192       529
20   9906       524
21   9875       514
22   8611       509
23   9748       497
24   8564       496
25   8636       496
26  10229       492
27  10235       489
28  10267       484
29   8178       483
30   8586       481
⋮   ⋮           ⋮
271   6269      34
272   8479      34
273   9858      34
274 188163      34
275   8234      33
276 177361      33
277   8344      32
278   4170      31
279   8460      31
280   8550      31
281   8295      30
282   8398      30
283   8690      30
284   9746      30
285   6547      29
286   9765      29
287   9776      29
288   9912      29
289   6351      28
290   8549      28
291   4064      27
292   6367      27
293   9878      27
294   8357      26
295  10213      26
296   7992      25
297   6631      24
298   7869      22
299 108893      21
300      1       1

# Wringting to Team.csv

In [75]:
team<-merge(p6,NumberOfGoals,by='team_api_id')
team
write.csv(team,file="team.csv")

     team_api_id team_long_name          BuildUpAll ChanceUpAll DefUpAll
1    1601        Ruch Chorzów             70        155         175
2    1601        Ruch Chorzów             99        186         144
3    1601        Ruch Chorzów            108        159         136
4    1601        Ruch Chorzów            108        159         136
5    1601        Ruch Chorzów            139        181         136
6    1601        Ruch Chorzów            133        176         136
7    1773        Oud-Heverlee Leuven     102        157         137
8    1773        Oud-Heverlee Leuven     102        157         137
9    1773        Oud-Heverlee Leuven     153        157         137
10   1957        Jagiellonia Białystok    80        150         210
11   1957        Jagiellonia Białystok    85        151         140
12   1957        Jagiellonia Białystok   127        163         141
13   1957        Jagiellonia Białystok   127        163         141
14   1957        Jagiellonia Białystok   130        146         162
15   1957        Jagiellonia Białystok   158        152         162
16   2033        S.C. Olhanense          100        155         155
17   2033        S.C. Olhanense          120        165         130
18   2033        S.C. Olhanense           85        134         105
19   2033        S.C. Olhanense           97        133         112
20   2033        S.C. Olhanense          147        134         105
21   2182        Lech Poznań              75        155         160
22   2182        Lech Poznań             121        186         144
23   2182        Lech Poznań             121        185         157
24   2182        Lech Poznań             121        185         157
25   2182        Lech Poznań             176        185         157
26   2182        Lech Poznań             147        196         153
27   2183        P. Warszawa              70        155         175
28   2183        P. Warszawa              80        162         140
29   2183        P. Warszawa              79        180         113
30   2183        P. Warszawa              79        131         139
⋮    ⋮           ⋮                       ⋮          ⋮           ⋮
1429  10268      Elche CF                171        164         158
1430  10268      Elche CF                151        164         158
1431  10269      VfB Stuttgart           100        200         175
1432  10269      VfB Stuttgart           112        178         140
1433  10269      VfB Stuttgart            92        170         134
1434  10269      VfB Stuttgart           100        189         137
1435  10269      VfB Stuttgart           168        164         140
1436  10269      VfB Stuttgart           155        172         117
1437  10278      Hércules Club de Fútbol  70        155         120
1438  10278      Hércules Club de Fútbol 109        152         159
1439  10278      Hércules Club de Fútbol 107        178         160
1440  10278      Hércules Club de Fútbol 107        178         160
1441  10278      Hércules Club de Fútbol 154        178         160
1442  10281      Real Valladolid          95        135         125
1443  10281      Real Valladolid         109        166         154
1444  10281      Real Valladolid         109        172         161
1445  10281      Real Valladolid         109        172         161
1446  10281      Real Valladolid         153        167         161
1447  10281      Real Valladolid         148        147         134
1448 108893      AC Arles-Avignon        115         95         115
1449 108893      AC Arles-Avignon        115        105         105
1450 108893      AC Arles-Avignon         56        132         112
1451 108893      AC Arles-Avignon         89        141         140
1452 108893      AC Arles-Avignon        141        132         154
1453 108893      AC Arles-Avignon        156        138         158
1454 158085      FC Arouca               174        160         109
1455 158085      FC Arouca               170        160         113
1456 208931      Carpi                   109        137         141
1457 208931      Carpi                   190        160         115
1458 274581      Royal Excel Mouscron    150        150         140
     GoalTotal
1    280
2    280
3    280
4    280
5    280
6    280
7    126
8    126
9    126
10   287
11   287
12   287
13   287
14   287
15   287
16   138
17   138
18   138
19   138
20   138
21   372
22   372
23   372
24   372
25   372
26   372
27   184
28   184
29   184
30   184
⋮    ⋮
1429  65
1430  65
1431 415
1432 415
1433 415
1434 415
1435 415
1436 415
1437  36
1438  36
1439  36
1440  36
1441  36
1442 170
1443 170
1444 170
1445 170
1446 170
1447 170
1448  21
1449  21
1450  21
1451  21
1452  21
1453  21
1454 101
1455 101
1456  37
1457  37
1458  71

# Reading Player CSV

In [76]:
player=read.csv("player.csv")
player

      X     player_api_id NoOfOccurances player_name
1      1    2625           90            Patryk Rachwal,18
2      2    2752           81            Diego Mainz
3      3    2768           71            Jose Dorado
4      4    2770           16            Ignacio Gonzalez
5      5    2790           50            Alberto Rey
6      6    2796            1            Javier Jimenez
7      7    2802          144            Pablo Hernandez
8      8    2805          131            Ruben Perez
9      9    2857            3            Ivan Perez
10    10    2862           17            Vicente Sanchez
11    11    2907            6            Gregory Lacombe
12    12    2973           16            Ugur Inceman
13    13    2977            5            David Rivas Rodriguez
14    14    2983           71            Jorge Molina
15    15    2984           38            Sergio Aragones
16    16    3140           42            Alexandre Hauw
17    17    3204           42            Marat Izmailov
18    18    3263           19            Kelly Berville
19    19    3264            1            Abdelmalek Cherrad
20    20    3316            6            Oscar Sanchez
21    21    3329           85            Vincent Euvrard
22    22    3377            1            Luca Belingheri
23    23    3441           74            Aleksander Radosavljevic
24    24    3512            4            Peter Halmosi
25    25    3517           17            Alexandr Kerzhakov
26    26    3520           70            Andrey Arshavin
27    27    4747           36            Lee Wilkie
28    28    4863           25            Boban Grncarov
29    29    4902           68            Iriney
30    30    4939           97            Tim Clancy
⋮     ⋮     ⋮             ⋮              ⋮
11031 11031 701154         2             Kylian Mbappe Lottin
11032 11032 703659         1             Colin Trachsel
11033 11033 704523         4             Christopher Nkunku
11034 11034 705484         4             Eray Cumart
11035 11035 706985         2             Jordan Lyden
11036 11036 710807         1             Jonatan Montiel
11037 11037 715642         1             Aissa Laidouni
11038 11038 716998         1             Sebastien Lamonge
11039 11039 717248         4             Felipe Augusto
11040 11040 717270         1             Antoine Rabillard
11041 11041 717557         4             Levi Garcia
11042 11042 719413         3             Dorian Caddy
11043 11043 720738         5             Charles Traore
11044 11044 721133        15             Rafa Soares
11045 11045 722766        13             Charly Musonda
11046 11046 723037         7             Wanderson Lima
11047 11047 725718         1             Dennis van der Heijden
11048 11048 726956         4             Cedric Itten
11049 11049 728125         2             Christopher McLaughlin
11050 11050 728414         1             Justin Hoogma
11051 11051 728478         1             Kamil Jozwiak
11052 11052 730065         1             Jorge Intima
11053 11053 733787         2             Linus Obexer
11054 11054 742405         1             Tom Davies
11055 11055 743720         1             Charles Pickel
11056 11056 744907         1             Greg Taylor
11057 11057 746419         2             Francisco Afonso
11058 11058 748432         2             Fynn Arkenberg
11059 11059 750435         1             Rees Greenwood
11060 11060 750584         1             Alexandre Azevedo
      overall_rating NumberofLeagues gk_all
1     63             1               153
2     72             1                53
3     75             1               128
4     74             2               148
5     73             1               144
6     69             1               340
7     82             2               146
8     76             1               141
9     72             1               143
10    76             1               146
11    68             1               135
12    72             1               147
13    82             1               104
14    75             1               139
15    75             1               364
16    69             1               136
17    81             1               156
18    67             1               115
19    62             1                98
20    71             1               108
21    64             1               130
22    72             1               138
23    71             1               138
24    75             1               143
25    82             1               149
26    86             1               159
27    73             1               128
28    66             1                54
29    77             1               145
30    64             1               116
⋮     ⋮              ⋮               ⋮
11031 65             1               42
11032 51             1               48
11033 62             1               43
11034 52             1               32
11035 58             1               53
11036 67             1               47
11037 59             1               61
11038 56             1               46
11039 64             1               59
11040 61             1               56
11041 64             1               49
11042 64             1               54
11043 55             1               52
11044 70             1               60
11045 71             1               36
11046 53             1               54
11047 60             1               54
11048 54             1               41
11049 50             1               49
11050 59             1               54
11051 56             1               54
11052 57             1               59
11053 51             1               45
11054 51             1               56
11055 50             1               53
11056 53             1               57
11057 59             1               42
11058 58             1               46
11059 60             1               48
11060 58             1               54

# Which are the top 10 players by overall rating?

In [77]:
result <- player %>% 
             group_by(player_api_id) %>%
             
             filter(overall_rating == max(overall_rating))%>%
            select(player_name,overall_rating) %>%
              arrange(desc(overall_rating))
head(unique(result),10)

Adding missing grouping variables: `player_api_id`

   player_api_id player_name       overall_rating
1  30981         Lionel Messi      94
2  30717         Gianluigi Buffon  93
3  30829         Wayne Rooney      93
4  30893         Cristiano Ronaldo 93
5  39854         Xavi Hernandez    92
6  39989         Gregory Coupet    92
7  30626         Thierry Henry     91
8  30627         John Terry        91
9  30657         Iker Casillas     91
10 30723         Alessandro Nesta  91

In [78]:
#head(
#    player[
#        order(player$overall_rating,decreasing=TRUE),
#    ]
#     [,
 #     c("player_name","overall_rating")
  #   ],n=10
#)

# Which are the top 10 goalkeepers by sum of gk attributes?

In [85]:
r21 <- player %>% 
             group_by(player_api_id) %>%
             #mutate(gk_all=gk_diving + gk_handling + gk_kicking + gk_positioning + gk_reflexes) %>%
             #filter(gk_all == max(gk_all))%>%
             select(player_name,gk_all) %>%
              arrange(desc(gk_all)) 
                 
head(unique(r21),10)
#r2<-result%>%arrange(desc(gk_all))
#unique(r2)

Adding missing grouping variables: `player_api_id`

   player_api_id player_name       gk_all
1   30717        Gianluigi Buffon  449
2   39989        Gregory Coupet    447
3   30859        Petr Cech         445
4   30657        Iker Casillas     442
5   27299        Manuel Neuer      440
6   30989        Julio Cesar       438
7   24503        Sebastian Frey    437
8   30726        Edwin van der Sar 436
9  182917        David De Gea      429
10  30660        Pepe Reina        428

# Which are the top 10 players by number of appearances (with any team they played with)?

In [87]:

head(unique(player%>% select(player_name,player_api_id,NoOfOccurances) %>% arrange( desc(NoOfOccurances))),10)

   player_name          player_api_id NoOfOccurances
1  Steve Mandanda       31293         300
2  Stephane Ruffier     41097         294
3  Gorka Iraizoz Moreno 33764         286
4  Samir Handanovic     42422         286
5  Hugo Lloris          26295         282
6  Tim Howard           31465         282
7  Joe Hart             31432         275
8  Cedric Carrasso      26168         268
9  Daniel Congre        26399         262
10 Moussa Sissoko       94550         260

# Which are the top 10 players by number of leagues they played in?

In [88]:
head(unique(player%>% select(player_name,player_api_id,NumberofLeagues) %>% arrange( desc(NumberofLeagues))),10)

   player_name           player_api_id NumberofLeagues
1  Gelson Fernandes       42119        6
2  Ricky van Wolfswinkel 116750        5
3  Filip Djuricic        178538        5
4  Radamel Falcao         22543        4
5  Jonathan De Guzman     24123        4
6  Almen Abdi             25816        4
7  Ibrahim Afellay        26434        4
8  Edson Braafheid        26489        4
9  Eljero Elia            26675        4
10 Danijel Pranjic        30477        4

# Reading Team CSV

In [89]:
team=read.csv("team.csv")
team

     X    team_api_id team_long_name          BuildUpAll ChanceUpAll DefUpAll
1     1   1601        Ruch Chorzów             70        155         175
2     2   1601        Ruch Chorzów             99        186         144
3     3   1601        Ruch Chorzów            108        159         136
4     4   1601        Ruch Chorzów            108        159         136
5     5   1601        Ruch Chorzów            139        181         136
6     6   1601        Ruch Chorzów            133        176         136
7     7   1773        Oud-Heverlee Leuven     102        157         137
8     8   1773        Oud-Heverlee Leuven     102        157         137
9     9   1773        Oud-Heverlee Leuven     153        157         137
10   10   1957        Jagiellonia Białystok    80        150         210
11   11   1957        Jagiellonia Białystok    85        151         140
12   12   1957        Jagiellonia Białystok   127        163         141
13   13   1957        Jagiellonia Białystok   127        163         141
14   14   1957        Jagiellonia Białystok   130        146         162
15   15   1957        Jagiellonia Białystok   158        152         162
16   16   2033        S.C. Olhanense          100        155         155
17   17   2033        S.C. Olhanense          120        165         130
18   18   2033        S.C. Olhanense           85        134         105
19   19   2033        S.C. Olhanense           97        133         112
20   20   2033        S.C. Olhanense          147        134         105
21   21   2182        Lech Poznań              75        155         160
22   22   2182        Lech Poznań             121        186         144
23   23   2182        Lech Poznań             121        185         157
24   24   2182        Lech Poznań             121        185         157
25   25   2182        Lech Poznań             176        185         157
26   26   2182        Lech Poznań             147        196         153
27   27   2183        P. Warszawa              70        155         175
28   28   2183        P. Warszawa              80        162         140
29   29   2183        P. Warszawa              79        180         113
30   30   2183        P. Warszawa              79        131         139
⋮    ⋮    ⋮           ⋮                       ⋮          ⋮           ⋮
1429 1429  10268      Elche CF                171        164         158
1430 1430  10268      Elche CF                151        164         158
1431 1431  10269      VfB Stuttgart           100        200         175
1432 1432  10269      VfB Stuttgart           112        178         140
1433 1433  10269      VfB Stuttgart            92        170         134
1434 1434  10269      VfB Stuttgart           100        189         137
1435 1435  10269      VfB Stuttgart           168        164         140
1436 1436  10269      VfB Stuttgart           155        172         117
1437 1437  10278      Hércules Club de Fútbol  70        155         120
1438 1438  10278      Hércules Club de Fútbol 109        152         159
1439 1439  10278      Hércules Club de Fútbol 107        178         160
1440 1440  10278      Hércules Club de Fútbol 107        178         160
1441 1441  10278      Hércules Club de Fútbol 154        178         160
1442 1442  10281      Real Valladolid          95        135         125
1443 1443  10281      Real Valladolid         109        166         154
1444 1444  10281      Real Valladolid         109        172         161
1445 1445  10281      Real Valladolid         109        172         161
1446 1446  10281      Real Valladolid         153        167         161
1447 1447  10281      Real Valladolid         148        147         134
1448 1448 108893      AC Arles-Avignon        115         95         115
1449 1449 108893      AC Arles-Avignon        115        105         105
1450 1450 108893      AC Arles-Avignon         56        132         112
1451 1451 108893      AC Arles-Avignon         89        141         140
1452 1452 108893      AC Arles-Avignon        141        132         154
1453 1453 108893      AC Arles-Avignon        156        138         158
1454 1454 158085      FC Arouca               174        160         109
1455 1455 158085      FC Arouca               170        160         113
1456 1456 208931      Carpi                   109        137         141
1457 1457 208931      Carpi                   190        160         115
1458 1458 274581      Royal Excel Mouscron    150        150         140
     GoalTotal
1    280
2    280
3    280
4    280
5    280
6    280
7    126
8    126
9    126
10   287
11   287
12   287
13   287
14   287
15   287
16   138
17   138
18   138
19   138
20   138
21   372
22   372
23   372
24   372
25   372
26   372
27   184
28   184
29   184
30   184
⋮    ⋮
1429  65
1430  65
1431 415
1432 415
1433 415
1434 415
1435 415
1436 415
1437  36
1438  36
1439  36
1440  36
1441  36
1442 170
1443 170
1444 170
1445 170
1446 170
1447 170
1448  21
1449  21
1450  21
1451  21
1452  21
1453  21
1454 101
1455 101
1456  37
1457  37
1458  71

# Which are the top 10 teams by sum of build up play attributes?

In [83]:
team <- team %>% 
             group_by(team_api_id) %>%
            filter(BuildUpAll == max(BuildUpAll))%>%
              select(team_long_name,BuildUpAll) %>%
              arrange(desc(BuildUpAll))

head(unique(team),10)

Adding missing grouping variables: `team_api_id`

   team_api_id team_long_name             BuildUpAll
1    9804      Torino                     209
2    8600      Udinese                    205
3    8194      Fortuna Düsseldorf         198
4    8033      Podbeskidzie Bielsko-Biała 193
5    8245      Korona Kielce              192
6    8024      Widzew Łódź                190
7    8244      Widzew Łódź                190
8  208931      Carpi                      190
9    9830      FC Nantes                  189
10   7943      Sassuolo                   188

# Which are the top 10 teams by sum of chance creation attributes?

In [90]:
team1 <- team %>% 
             group_by(team_api_id) %>%
            filter(ChanceUpAll == max(ChanceUpAll))%>%
              select(team_long_name,ChanceUpAll) %>%
              arrange(desc(ChanceUpAll))

head(unique(team1),10)

Adding missing grouping variables: `team_api_id`

   team_api_id team_long_name      ChanceUpAll
1  8543        Lazio               220
2  8697        SV Werder Bremen    216
3  9875        Napoli              215
4  8178        Bayer 04 Leverkusen 210
5  8191        Burnley             210
6  8344        Cardiff City        210
7  8456        Manchester City     210
8  8485        Aberdeen            210
9  8548        Rangers             210
10 8586        Tottenham Hotspur   210

# Which are the top 10 teams by sum of defense attributes?

In [91]:
team3 <- team %>% 
             group_by(team_api_id) %>%
            filter(DefUpAll == max(DefUpAll))%>%
              select(team_long_name,DefUpAll) %>%
              arrange(desc(DefUpAll))

head(unique(team3),10)

Adding missing grouping variables: `team_api_id`

   team_api_id team_long_name        DefUpAll
1  1957        Jagiellonia Białystok 210
2  7794        SC Bastia             210
3  8021        Zagłębie Lubin        210
4  8197        Leicester City        210
5  8344        Cardiff City          210
6  8350        1. FC Kaiserslautern  210
7  8466        Southampton           210
8  8481        AS Nancy-Lorraine     210
9  8483        Blackpool             210
10 8521        Stade Brestois 29     210

# Which are the top 10 teams by number of scored goals?

In [93]:
head(unique(team%>%arrange( desc(GoalTotal))%>% select(team_long_name,GoalTotal)),10)

   team_long_name    GoalTotal
1  FC Barcelona      849
7  Real Madrid CF    843
13 Celtic            695
19 FC Bayern Munich  653
25 PSV               652
31 Ajax              647
37 FC Basel          619
43 Manchester City   606
49 Chelsea           583
55 Manchester United 582